#!/bin/bash -e

# install all the config files from $SNAP/config/SERVICE/res/configuration.toml 
# into $SNAP_DATA/config
mkdir -p "$SNAP_DATA/config"
if [ ! -f "$SNAP_DATA/config/device-random/res/configuration.toml" ]; then
    mkdir -p "$SNAP_DATA/config/device-random/res"
    cp "$SNAP/config/device-random/res/configuration.toml" "$SNAP_DATA/config/device-random/res/configuration.toml"
    # do replacement of the SNAP_DATA and SNAP_COMMON environment variables in the config files
    sed -i -e "s@\$SNAP_COMMON@$SNAP_COMMON@g" -e "s@\$SNAP_DATA@$SNAP_DATA@g" "$SNAP_DATA/config/device-random/res/configuration.toml"
fi

# handle device-random device profile
cp "$SNAP/config/device-random/res/device.random.yaml" "$SNAP_DATA/config/device-random/res/device.random.yaml"
